jwtConfig:
  secretCode: justInCase@@
dependencies:
  bcrypt
  body-parser
  express
  jsonwebtoken
  mongoose
  shortid
db:
  url: mongodb://localhost/watcher
api:
  rotas:
    login: localhost:3000/api/login
    auth: localhost:3000/api/auth
